### ISSUE TITLE
다 좋은데 개선할 부분 이슈 남깁니다.

### ISSUE THREAD

**Issue by Johnjihwan** [eungyeole/velog-readme-stats#1]
안녕하세요 광주소프트웨어마이스터고 전지환 입니다!
보자마자 너무나도 좋은 것 같아서 바로 이용해 보는데요, 개시글 태그 부분을 감싸는 배경 컴퍼넌트 영역이 약간 모자란 것 같아 개선 요청드립니다!
<img width="327" alt="Screen Shot 2021-06-16 at 8 51 27 PM" src="https://user-images.githubusercontent.com/67095821/122214201-ca7d3280-cee4-11eb-903d-4d58a4a5fb66.png">

**Comment by eungyeole** [comment]
좋은 의견 감사합니다. 현재 영어의 경우에는 문제가없지만 
한글의 넓이가 제대로 계산되지 않아 해당문제가 발생하는것으로 추정됩니다.
최대한 빠르게 고쳐보도록 하겠습니다!

**Comment by eungyeole** [comment]
현재 어느정도 문제가 해소되어 반영되었습니다.
확인부탁드립니다.

**Comment by eungyeole** [comment]
해결되었습니다
