### ISSUE TITLE
게시글의 제목으로 특정할 수 있을까요?

### ISSUE THREAD

**Issue by chaa822** [eungyeole/velog-readme-stats#14]
게시글에 태그를 유니크하게 걸면 원하는 게시글을 표시할 수 있는데, 태그 개수가 너무 많아지는 것을 원하지 않습니다.

예를들어  "https://velog.io/@eungyeole/Velog-포스트로-Github를-꾸며보자"에서

타이틀인 "Velog-포스트로-Github를-꾸며보자"로 특정할 수 있도록 해주실 수 있을까요?

**Comment by eungyeole** [comment]
좋은 아이디어인것같네요!
한번 연구해보겠습니다

**Comment by eungyeole** [comment]
#15 에서 해당기능이 구현되었습니다. 자세한내용은 Readme 참조해주세요
