### ISSUE TITLE
Like가 가장 많은 포스트를 고정할 수 있는 기능을 제공해주실 수 있나요?

### ISSUE THREAD

**Issue by kshired** [eungyeole/velog-readme-stats#18]
안녕하세요 velog-readme-stats를 잘 사용하고 있는 사람입니다.

최신글을 보여주는 것도 좋지만, likes 가 가장 많은 포스트를 보여주는 기능도 있으면 좋을 것 같습니다.

**Comment by eungyeole** [comment]
먼저 프로젝트에 관심 주셔서 감사합니다.
해당 기능이 도입되면 정말 좋을 것 같아서 velog 코드를 보며 방법을 연구해 봤으나
하지만 아쉽게도 현재로서는 like가 가장 많은 글을 보여주는 기능은 velog에서 구현되지 않아 이 기능이 도입되긴 어려울 것 같아요
앞으로도 필요한 기능이 있으시다면 적극적으로 이슈 남겨주시면 꼼꼼히 살펴보고 반영될 수 있도록 노력하겠습니다!
