### ISSUE TITLE
velog api 사용 권한

### ISSUE THREAD

**Issue by juwon8891** [eungyeole/velog-readme-stats#24]
안녕하세요. 궁금해서 질문드립니다.
fetcher에서 velog api를 사용하시고 계시던데
혹시 velog api 사용 권한을 velopert님께 따로 받으셨는지 궁금합니다.

**Comment by eungyeole** [comment]
@juwon8891 
이점에 대해서 전혀 생각하고 있지 않았네요....
velopert님께 사용권한을 받은 적은 없습니다 ㅠㅠ

그러나 이점 중요하게 생각하고 있고 한번 가능한 채널을 통해 연락을 취해볼게요!
