### ISSUE TITLE
포스트 제목에 '<' 혹은 '>' 포함시 오류

### ISSUE THREAD

**Issue by changgun-park** [eungyeole/velog-readme-stats#26]
포스트 글 제목에 '<'이나 '>'이 포함되어 있을 때 오류가 발생합니다.

![velog_readme_error](https://user-images.githubusercontent.com/79077488/179478609-368250a7-8174-4e7a-8d12-02a09f994bd6.png)
![velog_readme_error_title](https://user-images.githubusercontent.com/79077488/179478619-e5615408-2782-4ae0-b0ca-7d906c83ca6b.png)

**Comment by eungyeole** [comment]
#27 같은 이슈로 파악됨

**Comment by eungyeole** [comment]
#32 PR에서 해당 문제를 수정하였습니다
