### ISSUE TITLE
PCDATA invalid Char value Error

### ISSUE THREAD

**Issue by minjj0905** [eungyeole/velog-readme-stats#27]
안녕하세요, 잘 사용중인데 렌더링이 안되길래 뭐지 싶어 봤더니 오류가 있어서 올려봅니다.

https://velog-readme-stats.vercel.app/api?name=minjj0905

<img width="573" alt="image" src="https://github.com/eungyeole/velog-readme-stats/assets/55120738/479f19b9-d289-40f4-952f-1d82d761b6d3">

오류가 생기는 조건은 모르겠습니다..! ㅜ

**Comment by eungyeole** [comment]
@minjj0905 아마 사진처럼 설명에 있는 맥 투명 문자(?) 때문인 것 같은데 한번 제거해 보시겠어요? 

![6D140FBF-8A27-4A6C-BE19-784B14FAB6C7](https://github.com/eungyeole/velog-readme-stats/assets/66717787/f0eb3b28-0b1d-4690-a793-a46d1320705b)

**Comment by minjj0905** [comment]
문제 찾아주셔서 감사합니다!
