### ISSUE TITLE
no name Error

### ISSUE THREAD

**Issue by Jinwon-Dev** [eungyeole/velog-readme-stats#28]
![image](https://github.com/eungyeole/velog-readme-stats/assets/106216912/f5a494fd-e834-4dcf-938a-4e4ff3918b87)

안녕하세요! 제작하신 기능을 사용하려고 하던 도중, 오류가 생겨서 이슈 남깁니다.
https://velog-readme-stats.vercel.app/api/list?name=jinony

**Comment by wsh096** [comment]
저도 지금 같은 오류가 발생하고 있네요. 잘 되다가 요런 오류가 뜨네요

**Comment by wsh096** [comment]
<svg xmlns="http://www.w3.org/2000/svg" width="430" height="160" viewBox="0 0 430 160" fill="none">
            
    <style>
        .header {
            font: bold 14px 'Segoe UI', Ubuntu, Sans-Serif;
            fill: #343A40;
            animation: fadeInAnimation 0.8s ease-in-out forwards;
        }
        .log-title { font: bold 14px 'Segoe UI', Ubuntu, Sans-Serif; fill: #212529 }
        .log-description { font-size: 12px; fill: #495057}
        .tag-item { font-size: 12px; fill: #0CA678;}
        .heart-count { font-size: 12px; fill: #495057;}
        .log-title:hover{ fill: #0CA678; text-decoration: underline;}
        .list-style{font-size:14px; fill: #212529; }
    </style>

            <rect data-testid="card-bg" x="0.5" y="0.5" rx="4.5" height="99%" stroke="#e4e2e2" width="429" fill="#fffefe" stroke-opacity="1"/>
            
    <g data-testid="card-title" transform="translate(25, 35)">
        <g transform="translate(0, 0)">
          <text x="0" y="0" class="header" data-testid="header">wsh096.log 's latest posts</text>
        </g>
    </g>
    
            
  <g data-testid="main-card-body" transform="translate(0, 45)">
  <svg data-testid="lang-items" x="25" width="400" height="400" viewBox="0 0 400 400">
      <g transform="translate(0, 0)">
          <text data-testid="lang-list" class="list-style" x="5" y="20">•</text>
          <a href="https://velog.io/@wsh096/북스터디자바-기술-면접-빈출-질문3-8가지-디자인-패턴-질문">
              <text data-testid="lang-name" x="20" y="20" class="log-title">[북스터디]자바 기술 면접 빈출 질문(3) 8가지 디자인 패턴 질문</text>
          </a>
          <text data-testid="lang-list" class="list-style" x="5" y="43">•</text>
          <a href="https://velog.io/@wsh096/북스터디자바-기술-면접-빈출-질문2-6가지의-인터페이스-관련-질문">
              <text data-testid="lang-name" x="20" y="43" class="log-title">[북스터디]자바 기술 면접 빈출 질문(2) 6가지 인터페이스 & 메서드 하이딩</text>
          </a>
          <text data-testid="lang-list" class="list-style" x="5" y="66">•</text>
          <a href="https://velog.io/@wsh096/개발자에게-멘토링과-멘티-활동이란">
              <text data-testid="lang-name" x="20" y="66" class="log-title">개발자의 멘토링 활동</text>
          </a>
          <text data-testid="lang-list" class="list-style" x="5" y="89">•</text>
          <a href="https://velog.io/@wsh096/북스터디자바-기술-면접-유명-질문1-11가지의-오버라이딩오버로딩-관련-질문">
              <text data-testid="lang-name" x="20" y="89" class="log-title">[북스터디]자바 기술 면접 빈출 질문(1) 11가지의 오버라이딩_오버로딩 관련 질문</text>
          </a>
      </g>
  </svg>
</g>
    
        </svg>
    
    
    
source를 읽어 보면 데이터 파싱은 잘 된 거 같은데 어디가 문제인지 계속 찾고 있네요. 개선되거나 문제 확인하면 업데이트 해두겠습니다.

**Comment by eungyeole** [comment]
@wsh096 , @Jinwon-Dev 
이슈 남겨주셔서 감사합니다! 
#32 PR에서 의심되는 문제를 수정했는데 확인 부탁드립니다!

**Comment by wsh096** [comment]
네! 잘 되는 거 확인했습니다. 너무 늦게 확인했네요 감사합니다!!!
