### ISSUE TITLE
벳지 생성 9글자 초과시 짤림

### ISSUE THREAD

**Issue by murphybread** [eungyeole/velog-readme-stats#29]
영어로9글자를 초과하는 벳지를 만들 때 잘려서 표기되는데 혹시 글자 수 제한을 풀 수 있을까요?

**Comment by eungyeole** [comment]
@murphybread 
이슈 남겨주셔서 감사합니다!
#32 PR에서 해당 문제를 수정했는데 한번 확인 부탁드립니다!

**Comment by murphybread** [comment]
확인결과 잘 나옵니다!
반영해 주셔서 감사합니다~
