### ISSUE TITLE
박스 사이즈 문의

### ISSUE THREAD

**Issue by dbwpghks56** [eungyeole/velog-readme-stats#30]
지금 박스 크기가 애매하게 커서 양옆으로 정렬이 안 됩니다.
혹시 크기를 조절하는 기능이나 크기를 조금 줄여주실 수 있나요??

만들어 주셔서 감사합니다! 예쁘게 잘 쓰고 있어요 😸 

![image](https://github.com/eungyeole/velog-readme-stats/assets/43091440/ad8b5e09-6e4e-40d4-82c1-c4441a63a5a2)

**Comment by eungyeole** [comment]
@dbwpghks56 한개 짜리와 리스트의 크기가 달라서 그런거죠 ㅠㅠ?

**Comment by dbwpghks56** [comment]
아 제가 한 개 짜리 두 개 나란히도 시도해봤는데 안 되더라구요 ㅠㅠ

**Comment by eungyeole** [comment]
아 높이가 달라서 양옆으로 했을때 안 이뻐 보이는거죠?

**Comment by eungyeole** [comment]
이건 한번 둘이 똑같이 만들 수 있을지 확인해 볼게요

**Comment by dbwpghks56** [comment]
아 아니요 저는 양옆으로 나오지 않는다는 거였습니다! 위에 보내드린 사진처럼이용
이게 편집 할때 프리뷰로 확인을 하면 한 줄로 잘 뜨는데 깃허브로 확인하면 다음줄로 넘어가더라구요.
- 깃허브 프로파일
![image](https://github.com/eungyeole/velog-readme-stats/assets/43091440/3201b10c-a4ba-4b73-b86b-1fc746507612)

- 프리뷰
![image](https://github.com/eungyeole/velog-readme-stats/assets/43091440/d12f26ba-43a2-4882-87af-56c2678bb203)

**Comment by eungyeole** [comment]
아 그런 문제라면 markdown 문법 말고 img 태그로 임베딩 시켜 보시는걸 추천 드립니다
하고 아래 처럼 넓이를 48% 정도 주면 이쁘게 나올 것 같아요

<img src="https://velog-readme-stats.vercel.app/api?name=eungyeole&tag=github" width=48% />

**Comment by dbwpghks56** [comment]
우오아!!!!! 이런 방법이 있었군요! 빠르게 알려주셔서 감사합니다
예쁘게 잘 쓰겠습니다 감사합니다! 🙇‍♂️
