### ISSUE TITLE
README 수정 건의

### ISSUE THREAD

**Issue by iixanx** [eungyeole/velog-readme-stats#33]
안녕하세요! 
다름이 아니라, 해당 레포지토리의 리드미 수정에 대해 건의드리려 합니다.

**특정 태그를 가진 최신글 가져오기**나 **카드색 바꾸기**, **상태카드와 최신글 연결하기**의 경우 해당 링크가 올바르게 작동하지 않아 badge가 제대로 띄워지지 않는 것으로 보입니다.

새롭게 사용하시는 분들을 위해 리드미의 해당 부분은 수정이 필요하다고 생각합니다.
<img width="909" alt="image" src="https://github.com/eungyeole/velog-readme-stats/assets/155030721/69351b94-6c76-4ba2-9a09-3a0e2b203d34">

**Comment by eungyeole** [comment]
이 이슈를 이제 봤네요.. 벨로그 업데이트 되면서 기존 API 지원이 불안정한 것 같아서 전체적으로 한번 손 보겠습니다.

**Comment by eungyeole** [comment]
수정 완료
