### ISSUE TITLE
포스트 뱃지 링크 관련

### ISSUE THREAD

**Issue by rachel5004** [eungyeole/velog-readme-stats#9]
안녕하세요!! 좋은 서비스 감사합니다 너무 맘에 들어서 후다닥 적용해봤어요...!☺
그런데 포스트 뱃지 관련해서 궁금한 점이 있습니다

최신 글 정보까지는 잘 가져오는데 링크까지 데려오는건 아닌게 맞나요??
링크가 자동으로 적용되는게 아니라 하드코딩 해줘야  해당 글로 연결됩니다ㅜ
리드미에 따로 나와있는게 없어 이슈에 올립니다!

**Comment by eungyeole** [comment]
먼저 사용해 주셔서 감사합니다. 현재는 말씀하신 대로 작동하는 것이 맞습니다 ㅠㅠ
하지만 카드에 링크를 걸 수 있는 방법을 알아 현재 연구 중에 있습니다. 적용이 되거나 혹은 적용이 어려울 때
코멘트 다시 남겨 드리겠습니다.

**Comment by eungyeole** [comment]
#10 PullRequest에서 해당기능이 추가되었고 Realse 1.1.1에 해당기능이 공개되었습니다. 
Readme를 확인해주세요
